### ISSUE TITLE
连加好友都没有，怎么测试啊，怎么加好友呢

### ISSUE THREAD

**Issue by Arthurshen98** [zhaoyang21cn/Android_Suixinliao#1]

**Comment by Arthurshen98** [comment]
我在应用宝上面下载了随心聊IM无法添加好友，—， —》

**Comment by Arthurshen98** [comment]
你这个我项目我也没运行成功，给个步骤可好，我用as

**Comment by JasonXiao001** [comment]
1 git clone 
2 android studio ->file -> open

**Comment by Arthurshen98** [comment]
我重新建立的工程，把你那个项目弄进去的，直接弄不知道缺少什么

**Comment by peter5** [comment]
Error:Unknown host 'maven.oa.com: nodename nor servname provided, or not known'. You may need to adjust the proxy settings in Gradle.
<a href="toggle.offline.mode">Enable Gradle 'offline mode' and sync project</a><br><a href="https://docs.gradle.org/current/userguide/userguide_single.html#sec:accessing_the_web_via_a_proxy">Learn about configuring HTTP proxies in Gradle</a>



一直报这个错误呀，怎么搞 as 2.2.2
