### ISSUE TITLE
项目中很多地方使用的MyApplication.getContext()都报空指针

### ISSUE THREAD

**Issue by Arthurshen98** [zhaoyang21cn/Android_Suixinliao#2]

**Comment by Arthurshen98** [comment]
例如：MyApplication.getContext().getString(R.string.summary_friend_added)
非常多类似的都报空指针，是为什么呢

**Comment by Arthurshen98** [comment]
在我项目中只要是涉及到MyApplication.getContext()的都报空指针，为什么呢，我也感觉疑惑，不应该啊

**Comment by Arthurshen98** [comment]
几乎所有的上下文都是用的Application的context，-。-

**Comment by JasonXiao001** [comment]
看看是否在AndroidManifest.xml 中声明MyApplication
